env: standard

runtime: nodejs20

instance_class: F1

service: cloud-friendly-site

handlers:
  - url: /(.*\.(gif|png|jpg|ico|txt|svg))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|ico|txt|svg)$
  - url: /.*
    script: auto
    secure: always

default_expiration: '12h'

automatic_scaling:
  min_instances: 0
  max_instances: 1
